### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by TI-130** [Meneltamar/fvtt-comprehend-languages#15]
Tried multiple languages but none of them worked. Type error is thrown as below:﻿

```
main.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
[Detected 1 package: comprehend-languages]
    at main.js:1:5688
    at async main.js:1:5102
    at async Promise.all (index 0)
    at async r (main.js:1:5714)
    at async Function.translateSelectedText (main.js:1:3211)
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
main.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
[Detected 1 package: comprehend-languages]
    at main.js:1:5688
    at async main.js:1:5102
    at async Promise.all (index 0)
    at async r (main.js:1:5714)
    at async Function.translateSelectedText (main.js:1:3211)
foundry.js:5099 Foundry VTT | Rendering JournalSheet
commons.js:6946 Foundry VTT | Created JournalEntry with id [h4bCHzkQ17PxGH4Y]
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
api-free.deepl.com/v…tag_handling=html:1 
 Failed to load resource: the server responded with a status of 403 ()
main.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
[Detected 1 package: comprehend-languages]
    at main.js:1:5688
    at async main.js:1:5102
    at async Promise.all (index 9)
    at async r (main.js:1:5714)
    at async t.translateSinglePage (main.js:1:667)
    at async Promise.all (index 0)
    at async t.translateButton (main.js:1:445)
```

**Comment by Meneltamar** [comment]
403 means forbidden (i.e. DeepL says you aren't allowed to do what you want
to do), so I assume that something is wrong with your token.
Are you using the free plan?

TI-130 ***@***.***> schrieb am Do., 8. Dez. 2022, 21:25:
